apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: bluegreen-health-check
spec:
  metrics:
  - name: error-rate
    interval: 30s
    count: 3
    failureLimit: 1
    consecutiveErrorLimit: 5
    provider:
      prometheus:
        address: http://monitoring-kube-prometheus-prometheus.monitoring:9090
        query: |
          scalar(
            sum(rate(
              container_cpu_usage_seconds_total{
                namespace="default",
                pod=~"oauth-api.*"
              }[2m]
            )) or vector(0)
          )
    successCondition: "result >= 0"
    failureCondition: "result < 0"
