---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCO40pDG57NVD3WGMNo6y4NntbTmrARRfLPfw0ApbOSsVjkfxbSwEGoe4pIAtvOB+ACqOxO8nzwft/iXXDvZ3kSh9PS+m/H5HJ3Fu1YJjaw7t38VtjDdlvbaAZ/aHDm4IutXevYbwC6GIV4e/4z1IHRcY7Xuk2jMe7qpPGWk7gmUoT1CGfBI/NbI6e2bLPb4mjdZxeIVPk48SEdvPLo7sLt8XsP+RLTC78DVQNNDnj2kGw9W8unpKwZhHKQQaI28PLV6q7pJC85bBgisJ9RGoRovs9GVUYJkVgeYFMF9GRj0UkSDasOhlPReduv9iRTA78PdnWzdsqL1Isg8Q39+jsSHUVEs1rZCceJzaDtMVKfj+t6TNTD/NGnPKBjLKlF71VWk9PZdq+R07m0qY9bFAIXFqQDbwuSEmFoiWmN2uIhXpTPpLR674Y8PPEPIMfBD+tg8o8x2jIRhg2o/1Vbn0KGEzLERzIaA5c7iB/Ee3BXTZhK6Nc0o0TNNbqiPbvCgwy3TPurh1EZ2rP1xRbb/ZOErl17RBzgPoE8DW8ifzP95b29o0Snqn/rdSzSI/wQ6w+Tk7foxagT9v7hpnbxraozIQDJswB2cVW7U2PnQH6TU20gsI3bHXXoIpV3argGDkkGC3s6CZEqiIwTtvutrZs+eMO+lRlGPGjbimJawHcA142m1DGWQPICOXs/2fdATVzOOAfYgqtQkrGvglmwMrXWdHXPb3HFQ9HI0lA3oL5xdw+Sk/mT7yk34m3+RYGxkelEw5mvvGpQBmoCunQDd5pOT17Tycij
    SECRET_KEY: AgBDBJjqtufgvbbEVe+qeh0xiNmo6x58FvclStMgdiRioXGNMbFkV2VrO6GGXtD4tOFal89HFyiTXyH9drokAHOFP7c0VNyPplLKq3zrJCEAzv8ro+VQU/Tm2h5e+ERhToVIffgobNDZ/A+kIC6lg76LR/dh+lRlmRr4Fs0XujBMeD4B9yxFQPhNG0SdTEmqJsRQWNidpV1ZDjtzfgCyj2I5uBKmZblfUFW8GymeO/2Lbex1+VNv2lb560DIf8ziPN58vwHMQFZiIa2G+yfFgvUPzktuE/0dWutTo950uTJdjMmXXzDj1IpbHxNp2QcVgxfhhPsKodIQkkuHrjSnTqhaH6R8I0sOq1xhaOFLQyPy5RnyxRTjtsrAKeE0Bs+sTIUneaOUQS1O+DnfmPYXLHOg2pzB18++XBHOsbxVbw+uWMR3leVTcldnL4MiY4PKbrW1lkYqJJ3FJoWTCBuFZaau53azjdVmbQQUc9gr/wMlJ8Ewhs89ue8iQ5Z8bKnq0RlJAWUO97uBvdkh4td9NYH+WcoxWIMCsdNAduPwM+qfLreeg715JABZoqIEbqq4XZYQw36CoJ6iW2zUw2vuV8SRmHdsDp1pRtRJjd7XbTNf9QIfNP0iVso+BdyStzo+7OYRtl13AoHOmwxVK05rz6Poyb8VMv40VySgEjxfp6oaCN0VxEnTO75kwpuVSZ+TK98iqV41JWj2cZ4CaCxIqZsCj9vCdiHuKfExbXH1kOTFaCI=
  template:
    metadata:
      name: app-secret
      namespace: default
    type: Opaque
