---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgA9EPAqK/NzAk/4pf/puus74Pejf0xVDGNRrEErKvQHbwbuEzpY1Kbwef1oKNXLN4XomKhby9atfhosMaA40X7YxOMzrFUZaXqf0yl3RQtvnnT0N8UCrW7PfWRlVFGKe/xWD6mjQpOEZZtFrH8V5VRfug/fBjwyaPo/8KVDY/DIm66g53vulx+36ohak889EoCeYlvMQlloPCkk44KDk8HUI5kPLiUFkKpxNQk9fpVr0KZQdQyKEv2oL7JgzCMeWEwmmdwvai3KRY1yoyfwCZVnYMDHkhfHDvDDLch69rmcv7JzKN3+f7B1bX5aJPWOvG34Tj/y5JZE8cl0tF6myoMpqHz+RgAL3eULs0he/ORvCuhSl2QwDi1YTT6zZ0meWrcCVsaZSCtqrTfTnFDF33ezToA98NOg8Pm5Voe19N3JPlYVhaVjVeBXMYrJioRqTgobsK87qkFj0yfkdEZeDnwostkW55ePLkPI0RUdwAjLd9zuKiCH8emjy9iwNIrWit8t2WbH+CMwAGRbS3X1bcLH8PbshBa2bcleBtwmh5SlogqfpQwaD/LIYV8JMGkmbIeuKa9zjd52i8V1CjT1pGNFQr69Wj6dvED5A8UXi7ZAdlEHOfO/b4TvvxlHidD2MnitOYsImdH7b82uFTj68C1JoO8q4mUpOwPwkemmidrJ+OGQMJdGRKmSHK8BbqL3Qh/9dEImF0PD17UhE4mD85zocABdT1REI2Y6w0746TryRUBsObWfxjom+vQ9m0IUykjucZA6DIMVqhN+keHJX5nqoY5p5s/8
    SECRET_KEY: AgBMauaM0cGj/MCixkAaGUNvS1IC6IWmZ3q5o1AoczOiye8NWIG2ivpUoUmEXAvrjH6qMSmMwJs6MV7fduyxK7gsUpxTOJpTKjh7UGpfH3VAjxaQy6+2JJfMKomNTEDLUkn/Mmj8HjLo9G526mjrsR01bg0BFPvnvxUWW09jAjJIjJorPdRT+3hx8y8uGjxt3NmiwpRAPbu1su0BKrG2oVgJ1IJo0AM+WeX0nQ1AyBf+x6Sd5L9cBZtgJgjg37EIk532vLEyKwMlDx6hzoIRRhXzuRqwbvmpjwQS3UQha/Rs1Q2b/auwn0kyhcZyc3h4eSoL8od4CgvjBxblf1TWOWRUX4nIof9lPHWETOjAVALEu/65n5sCUjZw8FgZ+2JizdhG2+F7mC6FlKzXM+op/8df7ycQna20DwvvxRpx6KD2NOpEwNK/2bROjxSpGygfVET4wiHH8/MyBV9F05ztNn1GYKY7ukVCQCM/Qhr+XBQwJhbI+pY3/BdqL0T1ula2g19HIxxKf/q3H2I5/jEOrE/HbooWxRLs+Co9LuijWu4lUZquvhtjI7GLPVNBcOHxxGJcmSPPf4JEysfKoq2QASq9SQrCX/0G1KHn3eXJ4+xxVh2OfYbgvWeklP1s+HfyMZ36OWgaAUKJ3gASrBcdz1yypQvVt8rEFAiWr06lrF6BOTymZYDPK4am78b3H4BcnYOFNpJB6QqSyOGIkEdgTqCorS2lnXhs9Rub4Hh6jLdlGGg=
  template:
    metadata:
      name: app-secret
      namespace: default
    type: Opaque
