apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      project: oauth-api

resources:
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-ingress.yaml
  - network-policy.yaml
  - app-sealed-secret.yaml
  - postgres-sealed-secret.yaml
