apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      project: oauth-api

resources:
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - app-rollout.yaml
  - app-service.yaml
  - app-service-preview.yaml
  - app-ingress.yaml
  - app-ingress-preview.yaml
  - bluegreen-analysis.yaml
  - canary-rollout.yaml
  - canary-service.yaml
  - canary-ingress.yaml
  - canary-analysis.yaml
  - network-policy.yaml
  - app-hpa.yaml
  - canary-hpa.yaml
  - app-vpa.yaml
  - app-sealed-secret.yaml
  - postgres-sealed-secret.yaml
  - snapshot-rbac.yaml
  - snapshot-cronjob.yaml
