apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      project: oauth-api

resources:
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-sealed-secret.yaml
  - postgres/db-snapshots/snapshot-rbac.yaml
  - postgres/db-snapshots/snapshot-cronjob.yaml
  - oauth-api/app-rollout.yaml
  - oauth-api/app-service.yaml
  - oauth-api/app-ingress.yaml
  - oauth-api/oauth-preview/app-service-preview.yaml
  - oauth-api/oauth-preview/app-ingress-preview.yaml
  - oauth-api/bluegreen-analysis.yaml
  - frontend/canary-rollout.yaml
  - frontend/canary-service.yaml
  - frontend/canary-ingress.yaml
  - frontend/canary-analysis.yaml
  - frontend/canary-hpa.yaml
  - oauth-api/autoscalers/app-hpa.yaml
  - oauth-api/autoscalers/app-vpa.yaml
  - oauth-api/app-sealed-secret.yaml
  - network-policy.yaml
