apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshot-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: snapshot-role
rules:
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: snapshot-rolebinding
subjects:
- kind: ServiceAccount
  name: snapshot-sa
roleRef:
  kind: Role
  name: snapshot-role
  apiGroup: rbac.authorization.k8s.io
