apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-api
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: oauth-api
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1"
            memory: "1Gb"
