apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-api
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: oauth-api
        resources:
          requests:
            cpu: "750m"
            memory: "768Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
